### ISSUE TITLE
Schematic for new EMS Bus Wi-Fi Gateway?

### ISSUE THREAD

**Issue by Th3M3** [bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz#22]
Hi.

Can or will you provide the current schematic of the _EMS Bus Wi-Fi Gateway_ wich includes the Wemos D1 Mini and the buck power regulator?

The Background is that I have to create my own PCB that will fit inside a already mounted cabinet.

**Comment by bbqkees** [comment]
I don't have it online but you can use the schematic from Proddy's wiki:
https://github.com/proddy/EMS-ESP/wiki/building-your-own-test-circuit

Just don't include the powercap C1, and lower R4 and R5 to around 360.
If you want to use jack power instead of the bus, disconnect the anode side of D7 from the bus and connect D7 directly to the power pin of the jack.
If you use jack power you dont need C2 and C4.

![](https://raw.githubusercontent.com/bbqkees/Nefit-Buderus-EMS-bus-Arduino-Domoticz/master/Documentation/EMS-bus-jack-pinout.JPG)

Also there is a small mistake in that schematic. R11 should be 100k and R10 is 10k.

A 500mA buck is enough.

The parts list for SMD is in the Documentation folder of this repository.
